services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
